const products = [
  {
    id: 1,
    name: "Espresso Shot",
    category: "coffee",
    price: 120,
    image: require("../images/1.png"),
  },
  {
    id: 3,
    name: "Iced Latte",
    category: "coffee",
    price: 180,
    image: require("../images/3.png"),
  },
  {
    id: 4,
    name: "Caramel Macchiato",
    category: "coffee",
    price: 160,
    image: require("../images/4.png"),
  },
  {
    id: 5,
    name: "Flat White",
    category: "coffee",
    price: 170,
    image: require("../images/5.png"),
  },
  {
    id: 7,
    name: "Chocolate Cupcake",
    category: "cupcakes",
    price: 80,
    image: require("../images/7.png"),
  },
  {
    id: 8,
    name: "Vanilla Cupcake",
    category: "cupcakes",
    price: 85,
    image: require("../images/8.png"),
  },
  {
    id: 9,
    name: "Red Velvet Cupcake",
    category: "cupcakes",
    price: 100,
    image: require("../images/9.png"),
  },
  {
    id: 10,
    name: "Carrot Cupcake",
    category: "cupcakes",
    price: 95,
    image: require("../images/10.png"),
  },
  {
    id: 11,
    name: "Croissant",
    category: "pastries",
    price: 90,
    image: require("../images/11.png"),
  },
  {
    id: 12,
    name: "Blueberry Muffin",
    category: "pastries",
    price: 95,
    image: require("../images/12.png"),
  },
  {
    id: 13,
    name: "Grilled Cheese Sandwich",
    category: "sandwiches",
    price: 150,
    image: require("../images/13.png"),
  },
  {
    id: 14,
    name: "Avocado Toast",
    category: "breakfast",
    price: 180,
    image: require("../images/14.png"),
  },
  {
    id: 15,
    name: "Cold Brew Coffee",
    category: "coffee",
    price: 160,
    image: require("../images/15.png"),
  },
  {
    id: 16,
    name: "Fruit Smoothie",
    category: "smoothies",
    price: 120,
    image: require("../images/16.png"),
  },
  {
    id: 17,
    name: "Carrot Cake",
    category: "pastries",
    price: 140,
    image: require("../images/17.png"),
  },
  {
    id: 18,
    name: "Chocolate Milkshake",
    category: "drinks",
    price: 180,
    image: require("../images/18.png"),
  },
  {
    id: 19,
    name: "Chicken Sandwich",
    category: "sandwiches",
    price: 200,
    image: require("../images/19.jpg"),
  },
  {
    id: 20,
    name: "Turkey Sandwich",
    category: "sandwiches",
    price: 210,
    image: require("../images/20.png"),
  },
  {
    id: 21,
    name: "BLT Sandwich",
    category: "sandwiches",
    price: 180,
    image: require("../images/21.png"),
  },
  {
    id: 22,
    name: "Ham and Cheese Sandwich",
    category: "sandwiches",
    price: 190,
    image: require("../images/22.png"),
  },
];

export default products;
